# Generated by Django 3.2.10 on 2022-01-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0002_alter_shopuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="avatar",
            field=models.ImageField(default="users_avatars/default.jpg", upload_to="users_avatars"),
        ),
    ]
