# Generated by Django 3.2.10 on 2022-01-29 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_alter_shopuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='auth_key',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='auth_key_is_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 7, 29, 46, 309300, tzinfo=utc)),
        ),
    ]
