# Generated by Django 3.2.10 on 2022-01-31 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_user_model_extend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='auth_key_is_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 17, 7, 25, 308626, tzinfo=utc)),
        ),
    ]
