# Generated by Django 3.2.10 on 2022-01-31 17:46

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0006_alter_shopuser_auth_key_is_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="auth_key_is_expired",
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 17, 46, 46, 707561, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name="ShopUserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tagline", models.CharField(blank=True, max_length=128, verbose_name="теги")),
                ("aboutMe", models.TextField(blank=True, max_length=512, verbose_name="о себе")),
                ("interests", models.TextField(blank=True, max_length=256, verbose_name="интересы")),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "Муж"), ("F", "Жен")], max_length=1, verbose_name="пол"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
