# Generated by Django 3.2.10 on 2022-02-02 12:24

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0008_create_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="auth_key_is_expired",
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 12, 24, 38, 99590, tzinfo=utc)),
        ),
    ]
