# Generated by Django 3.2.10 on 2022-02-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_alter_shopuser_auth_key_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='auth_key_is_expired',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
