# Generated by Django 3.2.10 on 2022-02-12 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0010_alter_shopuser_auth_key_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='auth_key_is_expired',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 8, 53, 46, 568017, tzinfo=utc)),
        ),
    ]
